CREATE TABLE MOVIE
   (CODE NUMBER(4,0) primary key, 
	TITLE VARCHAR2(50 BYTE), 
	PRICE VARCHAR2(10 BYTE), 
	DIRECTOR VARCHAR2(200 BYTE), 
	ACTOR VARCHAR2(200 BYTE), 
	SYNOPSIS VARCHAR2(2000 BYTE));
    
    CREATE TABLE MOVIE_ATTACH 
   (UUID VARCHAR2(100 BYTE) not null primary key, 
	UPLOADPATH VARCHAR2(200 BYTE) NOT NULL , 
	FILENAME VARCHAR2(100 BYTE) NOT NULL , 
	FILETYPE CHAR(1 BYTE), 
	CODE NUMBER(10,0));
    
alter table movie_attach add CONSTRAINT PK_MOVIE_ATTACH PRIMARY KEY(UUID);

alter table movie_attach add CONSTRAINT FK_MOVIE_ATTACH foreign key(CODE)
REFERENCES Movie(code);
     
 
     